Runtime Error
Error: ./src/components/ui/carousel.tsx:9:1
Export useEmblaCarousel doesn't exist in target module
   7 |   EmblaPluginType,
   8 | } from "embla-carousel";
>  9 | import { useEmblaCarousel } from 'embla-carousel-react'
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  10 |
  11 | import { cn } from "@/lib/utils";
  12 |

The export useEmblaCarousel was not found in module [project]/node_modules/embla-carousel-react/esm/embla-carousel-react.esm.js [app-client] (ecmascript).
Did you mean to import default?
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.